### ISSUE TITLE
同款主板的机型fx50j，独显不同但已屏蔽，故可用您的efi

### ISSUE THREAD

**Issue by holwell** [sxz799/zx50jx4200_hackintosh#13]
当前版本：10.15.5
已知问题：1.clover引导无限重启，oc引导完美 2.待机息屏后，应该就是睡眠状态，再次激活会死机重启。3.脚本可修复耳机，但耳机插拔麦克风失效，重启恢复 4.触摸板无法驱动
最后：感谢分享，折腾黑苹果不多，能用到楼主的现成efi非常感谢，也已经非常满足了，祝生活愉快~

**Comment by smafaith** [comment]
我同款fx50jk4200，clover总是无法引导啊，楼主的oc不见了，您那边还有可用的吗 @holwell

**Comment by xxyangyoulin** [comment]
> 我同款fx50jk4200，clover总是无法引导啊，楼主的oc不见了，您那边还有可用的吗 @holwell

历史中应该是还存在的吧
