### ISSUE TITLE
求一下oc配置

### ISSUE THREAD

**Issue by zhuangjiahong** [sxz799/zx50jx4200_hackintosh#17]
大佬可以分享一下你的oc引导内容吗的，我就除了音频无法驱动，其他都好了，麻烦看到发我一下，谢谢，太难了，我的appalc死活无法加载，我们是同一款的声卡

**Comment by xxyangyoulin** [comment]
git reset --hard d22d5b11acd2db4ed19f466475df9d632751eaac
