### ISSUE TITLE
HDMI外接显示器会无限重启？

### ISSUE THREAD

**Issue by LeoFeng233** [sxz799/zx50jx4200_hackintosh#2]

**Comment by LeoFeng233** [comment]
我的zx50jx4200在HDMI外接显示器的情况下读条的一半会直接重启，如果不拔掉外接显示器会无限重启，只有在笔记本单独启动进入系统之后重新插上HDMI才能正常使用，请问这是我的个例吗？

**Comment by danandnda** [comment]
可能不是外接显示器的问题，我也是用的这个efi（不过网卡是dw1820a）我读条的时候也会重启。不过是有时候，我没有外接，所以应该是efi有点问题
