### ISSUE TITLE
修复USB 3.0

### ISSUE THREAD

**Issue by Shaloc** [sxz799/zx50jx4200_hackintosh#4]
在Commit `#bb11d7dea9d5368e49ab865e254789c70fd3dcf7` 之前，在`EFI/Clover/config.plist`里删除或禁用`change EHC1 to EH01` `change EHC2 to EH02` `change _DSM to XDSM`即可修复USB 3.0。

目前还没有发现这个操作会导致什么其他问题。

![截屏2019-10-14上午12 15 10](https://user-images.githubusercontent.com/24523674/66734377-b7fd4c80-ee17-11e9-85c5-a39878cb4509.png)
![截屏2019-10-14上午12 16 14](https://user-images.githubusercontent.com/24523674/66734412-d82d0b80-ee17-11e9-8b3b-4019f9cfcbc8.png)

**Comment by sxz799** [comment]
更新了
重新提取了dsdt和ssdt

**Comment by sxz799** [comment]
> 在Commit `#bb11d7dea9d5368e49ab865e254789c70fd3dcf7` 之前，在`EFI/Clover/config.plist`里删除或禁用`change EHC1 to EH01` `change EHC2 to EH02` `change _DSM to XDSM`即可修复USB 3.0。
> 
> 目前还没有发现这个操作会导致什么其他问题。
> 
> ![截屏2019-10-14上午12 15 10](https://user-images.githubusercontent.com/24523674/66734377-b7fd4c80-ee17-11e9-85c5-a39878cb4509.png)
> ![截屏2019-10-14上午12 16 14](https://user-images.githubusercontent.com/24523674/66734412-d82d0b80-ee17-11e9-8b3b-4019f9cfcbc8.png)

更新了 重新提取的dsdt和ssdt
