### ISSUE TITLE
fn+f5，f6调节亮度大小没用

### ISSUE THREAD

**Issue by birpg** [sxz799/zx50jx4200_hackintosh#6]
fn+f7关闭屏幕可以用

**Comment by jianghuke** [comment]
10.15.1亮度调节不能用

**Comment by sxz799** [comment]
快捷键设置f5 f6不需要➕fn

**Comment by jianghuke** [comment]
感谢大佬回复！我就是用快捷键设置的，希望大佬多多更新完善 macos 10.15 ！大老之前做的macos 10.14非常完美！最主要不用不用换网卡还可以投屏！！！我用的是小米电视。

已从 Outlook Mobile<https://aka.ms/blhgte> 发送

________________________________
