### ISSUE TITLE
随航功能不可使用及相关问题

### ISSUE THREAD

**Issue by DaenerysAlextratza** [sxz799/zx50jx4200_hackintosh#9]
当前的问题：根据苹果支持网站公布的数据，沿用MacBook pro11,2机型，则无法使用10.15系统下的随航功能。

我的尝试：我使用hackintool生成了MacBook Pro13,3序列号、主板序列号、smUUID，仅修改了config.plist中smBIOS的相关信息。重启后可使用有线随航功能，但蓝牙不可用（部分连续互通无法实现）、无法检测到2.4ghzWIFI信号。

请问：目前是否有能支持随航功能的修改方案？

**Comment by sxz799** [comment]
远景论坛有开启随航的脚本
不过不支持hevc解码的处理器不建议使用随航
